### ISSUE TITLE
Outgoing Caller Id unknown 

### ISSUE THREAD

**Issue by drx1331** [penn5/hwims-java#4]
Outgoing Caller id shown as unknown

**Comment by penn5** [comment]
Maybe fixed by reverting fbf782ce9f82ff9a7d4c7d662be632316d5e901a

**Comment by penn5** [comment]
Resolved as of e09a4b81f6e7f86d9a9465028e2b7124032a68bc and 175505af7b5764c13d0fc84ee2b49c40c8dca611
