### ISSUE TITLE
Missing '+' sign in some regions, but not needed in other regions

### ISSUE THREAD

**Issue by vatsalchandan** [penn5/hwims-java#7]
Incoming calls are missing '+' sign before country code so when we try to recall them, it says invalid number

**Comment by penn5** [comment]
Please can you test the output of https://dev.azure.com/HwIms/HwIms/_build/results?buildId=24 I think I fixed it

**Comment by penn5** [comment]
Some extreme hackery will be needed as in some regions a + is needed whereas in others a + breaks it

**Comment by penn5** [comment]
@penn5 https://developer.android.com/reference/android/telephony/PhoneNumberUtils.html#formatNumberToE164(java.lang.String,%20java.lang.String) might help here, but we need to know the mcc

**Comment by penn5** [comment]
Should be resolved as of:
0aa84eb14ada62735ddf050a10d1af9e3fbabd86
1f2f65a9074accd556104b826158b4a17dad02ec
